### ISSUE TITLE
Teste da classe Estacionamento

### ISSUE THREAD

**Issue by AndreAugusto0908** [DisciplinasProgramacao/projeto3-g7#10]

**Comment by AndreAugusto0908** [comment]
Esperando a classe campeonato ficar pronta. 

@joaocaram

**Comment by AndreAugusto0908** [comment]
O primeiro commit da classe teste está incompleto porque a classe "Campeonato" não está funcionando.

**Comment by AndreAugusto0908** [comment]
Teste classe estacionamento Finalizada

**Comment by joaocaram** [comment]
Verificar testes:  cada um deve ter seu assert

**Comment by AndreAugusto0908** [comment]
Todos os testes tem seu assert
